#! /bin/sh

sxhkd &
compton &
feh --bg-center Pictures/Wallpapers/wallhaven-399gz6_1920x1080.png &
$HOME/.config/polybar/launch.sh &

bspc monitor -d WEB MUSIC TTY CODE EDIT VI VII VIII IX X

bspc config border_width         2

bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a spotify desktop='^2' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

