#!/bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh &
/usr/bin/lxpolkit &
feh --bg-scale ~/Pictures/Wallpapers/thc.png &

bspc monitor -d Web Term Music Code Files Edit Comm Steam IX X

bspc config border_width         1
bspc config window_gap           12
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config focused_border_color "#d8dee9"
bspc config normal_border_color "#4c566a"

bspc rule -a firefox desktop=Web follow=on
bspc rule -a Alacritty desktop=Term follow=on
bspc rule -a spotify desktop=Music follow=on
bspc rule -a rhythmbox desktop=Music follow=on
bspc rule -a code desktop=Code follow=on
bspc rule -a Thunar=Files follow=on
bspc rule -a gimp desktop=Edit follow=on
bspc rule -a discord-canary desktop=Comm follow=on
bspc rule -a Steam desktop=Steam follow=on
