#! /bin/sh

xsetroot -cursor_name left_ptr &
sxhkd &
picom &
$HOME/.config/polybar/launch.sh &
/usr/bin/lxpolkit &

# Set a random wallpaper from a wallpaper directory
# sh /home/grtcdr/Scripts/randwallp.sh &
feh --bg-scale ~/Pictures/Wallpapers/arch.png

bspc monitor -d WEB TTY MUS CODE EDIT COMM GAME VIII IX X

bspc config border_width         2
bspc config window_gap           10
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config focused_border_color "#d8dee9"
bspc config normal_border_color "#4c566a"

bspc rule -a firefox desktop='^1' follow=on
bspc rule -a alacritty desktop='^2' follow=on
bspc rule -a spotify desktop='^3' follow=on
bspc rule -a code desktop='^4' follow=on
bspc rule -a gimp desktop='^5' follow=on
bspc rule -a discord-canary desktop='^6' follow=on
